version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      SUPPORT_GROUP: $SUPPORT_GROUP
      BOT_TOKEN: $BOT_TOKEN

      
